name: Auto Extract and Push M3U8

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Repository-ni klonla
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Mövcud faylları yoxla
        run: ls -la

      - name: Python və Chrome quraşdır
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Skripti işə sal
        run: python script.py

      - name: Dəyişiklikləri yoxla və push et
        run: |
          if [[ -s "token.txt" ]]; then
            echo "M3U8 token tapıldı, Git-ə push edilir..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add token.txt
            git commit -m "Auto-update token.txt"
            git push
          else
            echo "Xəta: token.txt faylı boşdur və ya tapılmadı."
            exit 1
          fi
