name: M3U8 Fetch and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Hər saatda bir dəfə işləsin

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Repozitoriyanı yoxla
      uses: actions/checkout@v2

    - name: Python quraşdır
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Tələbləri quraşdır
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Skripti işlə
      run: |
        python fetch_m3u8.py  # Burada skriptin adını uyğunlaşdırın, əgər `fetch_m3u8.py` deyilsə

    - name: Dəyişiklikləri Git-ə yüklə
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add token.txt script.log
        git commit -m 'Auto-update token.txt and log'
        git push
