name: m3u8-extractor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - selenium
  - requests
  - webdriver-manager
  - pip
  - chromedriver-autoinstaller
  - pip:
    - chromedriver-autoinstaller
