name: Run Python script with Selenium

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y libgconf-2-4  # Eğer lazım olarsa

    - name: Run Python script
      run: python update_token.py
      env:
        DISPLAY: :99
