name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxslt-dev  # Libxml2 və libxslt paketlərini quraşdırır
        pip install --upgrade pip
        pip install -r requirements.txt  # Burada bütün asılılıqları quraşdırır
        pip install pytest  # pytest modulunu ayrıca quraşdırır

    - name: Run tests
      run: |
        pytest  # pytest testləri tapıb işlədir
