name: Update Token Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Hər 30 dəqiqədən bir işlə

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver-manager
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y libgdk-pixbuf2.0-0 libxss1
        sudo apt-get install -y libasound2-dev libxss1 libgdk-pixbuf2.0-0
        sudo apt-get install -y chromium-browser

    - name: Run update token script
      run: python update_token.py
