name: Run Python Script

on:
  push:
    branches:
      - main  # Main branch-a push edildikdə işə düşəcək
  schedule:
    - cron: "0 * * * *"  # Hər saat başı çalışsın

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # requirements.txt faylını istifadə edirik

      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | sed 's/\..*//')
          wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run script
        run: python get_m3u8_link.py  # Skriptin adı
