name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Python versiyasını uyğunlaşdırın

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requirements.txt faylından asılılıqları quraşdırır

    - name: Run the script
      run: |
        DISPLAY=:99.0 python get_token.py  # Skriptinizi burada işə salırıq
