name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromedriver
        sudo apt-get install -y libglib2.0-0 libnss3 libxss1 libgdk-pixbuf2.0-0 libasound2

    - name: Run tests
      run: |
        DISPLAY=:99.0 python get_token.py
