name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Burada Python versiyanızı uyğunlaşdırın

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Əgər `requirements.txt` varsa, bu faylı istifadə edin

    - name: Install requests
      run: pip install requests  # requests modulunu quraşdırırıq

    - name: Run the script
      run: |
        DISPLAY=:99.0 python get_token.py
