name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Python versiyasını uyğunlaşdırın

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests github

    - name: Install Chromium and Chromedriver
      run: |
        sudo apt update
        sudo apt install -y chromium-browser
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Run the script
      run: |
        DISPLAY=:99.0 python get_token.py  # Skriptinizi burada işə salırıq
